### ISSUE TITLE
Remove leap day

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#35]
@danicalombardozzi noted that all our test runs fail in Feb 2020.

@ddurden, CLM doesn't know what to do with leap days and they must be removed from datasets.

More broadly, this introduces challenges in how to handle other high frequency data that we may encounter.  
For the tower forcing and evaluation data it will help us out a bunch if the NEON generated data removes leap days. 
@negin513, for new data we may want to compare with model output this is something we can consider

**Comment by wwieder** [comment]
@ekluzek noted that you can run NEON sites with a Gregorian calendar. And you can make sure the atm forcing data has the calender set to Gregorian. I suspect that's far better than removing it after the fact. The model can run for a Gregorian calendar.

@ddurden we'll resolve this on the NCAR end.

**Comment by ekluzek** [comment]
You might want to reopen this. Because the data from NEON should set the calendar to *something*, either "noleap" or "gregorian" This should be added to the time dimension. See the above CTSM issue for some details on this.

I think it should be set to "gregorian" both in the NEON data and for how CTSM runs with it.

You probably want to update the name of this issue to have it just say to add the calendar attribute to the time coordiinate.

**Comment by wwieder** [comment]
Sorry @ddurden I guess we need some changes to the "time" coordinate variable for CLM to handle this correctly
	`time:calendar = "gregorian" ;`

**Comment by ekluzek** [comment]
@ddurden just to let you know setting this attribute is critical for us at NCAR, because otherwise it assumes a "no-leap" calendar by default without it. There is then a contradiction when you have data for Feb/29th, but also Mar/1st in a no-leap calendar. So the best way for us to handle it is to have the calendar declared as an attribute to explicitly say it's "gregorian". Calendar is a standard attribute for time in the CF convention, and "gregorian" one of the values allowed. "standard" could also be used, but we'd have to extend our code to handle it.

https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html

**Comment by ddurden** [comment]
@wwieder  and @ekluzek , I'll make this change and rerun update the files in S3.

**Comment by ddurden** [comment]
BART and OSBS have been rerun and updated on S3, please let me know if the added calendar metadata solved this issue.
![image](https://user-images.githubusercontent.com/8151457/118824159-9c75e580-b887-11eb-9e10-1df9727d9730.png)

**Comment by negin513** [comment]
Thanks, @ddurden for adding the `calendar` attribute for OSBS and BART.

I've tested the OSBS site and it does not seem like this resolved our issue. 

 I am putting the detailed discussion of what I've done [here](https://github.com/ESCOMP/CTSM/issues/1373#issuecomment-844805082).

**Comment by ddurden** [comment]
@negin513  and @wwieder , it looks like this issue has been resolved now. Can we close this issue?

**Comment by wwieder** [comment]
yes, after it been corrected on data for other sites.

**Comment by negin513** [comment]
@ddurden Yes, this issue is resolved. :-)
I mentioned the progress [here](https://github.com/ESCOMP/CTSM/issues/1373#issuecomment-845399903) in [the related CTSM issue](https://github.com/ESCOMP/CTSM/issues/1373). Added the links here for future reference. 

@ddurden Please make sure the `calendar` attribute is added for the other NEON sites before closing this issue. 
Please let us know when you updated the files for NEON sites, so I can update them on our local system. Thanks for your help!

**Comment by ddurden** [comment]
@negin513 , all sites that have been processed are updated with the `calendar` attribute.

**Comment by negin513** [comment]
@ddurden Great! Thanks!
