### ISSUE TITLE
How do we know when updated data are available?

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#39]
This is a challenge for both 
- tower data (.nc files) as well as 
- Surface data (.csv files)

CESM uses creation dates in the file name, but I think this was not desirable on the NEON side.  
What's the best way to know if our local copy is different from the one in the S3 bucket, especially this as we correct / modify datasets?

**Comment by wwieder** [comment]
is this something that NCAR can handle using `check sum` functionality on the download from the S3 bucket @ekluzek or @jedwards?

**Comment by ddurden** [comment]
What about using the created_on metadata in the files?
![image](https://user-images.githubusercontent.com/8151457/118686411-f7e59c00-b7d1-11eb-90ab-d78f2b95658a.png)

**Comment by wwieder** [comment]
I'm not sure this works on our intake scripts, but maybe it can? I'll leave that up to Erik or Jim to weigh in on.
@ddurden, do you have recommendations if there are changes to the `.csv` files for the surface datasets?

**Comment by ekluzek** [comment]
I do encourage the idea of having some metadata on the files themselves to document when created and that sort of thing. So I endorse doing that. In our system when files are updated we create a new one with a later creation date in the filename. And then we largely assume we have the latest file if we've got a file with that name. 

Now, to prevent/detect file corruption we also have a mechanism where we store the checksum of the files on the server. So then you can compare the checksum of the file after you download it to the checksum on the text file with the list of checksums to make sure they agree. If not you know there's a problem with the download, or the file got corrupted while on disk.

Jim knows better about how this checksum business works. I think the main difference here is that if we know the contents of files can change we'll have to always download the file with the checksums even if we have it, because we know they can change.

**Comment by ekluzek** [comment]
To be more clear, yes @ddurden please add that metadata to all of the files. We'll have Jim work on the checksum verification that the files are correct as a way to know if we have the latest files. He's on vacation now, but when he gets back he should work on that.

@ddurden the other thing that seems could be done would be to have a listing of the files in the bucket that includes the creation date. That way you could download the latest version of that file to see if any files were updated since you last downloaded.

**Comment by ddlenz** [comment]
@ddurden @ekluzek @jedwards @wwieder https://neon-ncar.s3.data.neonscience.org/listing.csv now includes last_modified

**Comment by ddurden** [comment]
created_on field also in the netCDF file metadata, so I think we can close this ticket. Please let me know if something else is remaining @ekluzek @wwieder @jedwards @ddlenz

**Comment by jedwards4b** [comment]
This is addressed in #1411 by downloading the data anew for each case and not attempting to put it into the standard cesm inputdata location.  Since this is 1D data it's very fast.
