### ISSUE TITLE
surface data issues

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#44]
There are a number of issues we should likely discuss about surface data being provided by NEON for CLM simulation, mainly the soil profile data from the megapit.

One issue is organic horizons in the data,  which obviously don't have soil texture data.  Should O-horizon data still be included, and if so, what does CLM need to run (i.e. do we need to provide some soil texture information @dlawrenncar, @ekluzek, 

A second issue is with potential errors in the data being provided @ddurden (e.g. 
-[ ] PUUM has two samples for 0-17 cm depth and no bulk density for the O-horizon data)
-[ ] HEAL has bulk density for a C-horozon sample < 0.5.  Is this an error in the raw data?
-[ ] Others likely exist, but @negin513 is going to generate plots from all the sites to facilitate this discussion

**Comment by ekluzek** [comment]
You currently are going to get soil information from the global soil datasets. So soil texture, depth, color, and amount of organic in the soil. If you want to customize any of those for the NEON site then we'll need to get those values and change them in the modify script. If you do have observations on any of those things you are going to want to get them on the surface dataset.

All of those are also with depth other than soil color, but you likely only have observations near the surface so you'll need to just enter the surface levels you have info on.

**Comment by wwieder** [comment]
This seems like a good option, @ekluzek- basically if NEON is missing for a given layer, stick with the default values.

**Comment by negin513** [comment]
I plotted the profile of the surface dataset variables that are updated using neon dataset, comparing the original values and the updated values from neon.

The plots for all neon sites are in the following shared folder:
https://drive.google.com/drive/folders/1oUXdncv-2ilwpY-39L-HRkqm3gzJB2uP?usp=sharing

Each plot includes subplots of original and modified variables (i.e.  PCT_CLAY, PCT_SAND, ORGANIC, and zbedrock).


These plots reveal some issues with data from neon sites that @wwieder mentioned above. 

For example, for the [TOOL site](https://drive.google.com/file/d/1ZpJBOMb8WD6bQzx2WpEyyqfZzlls67tH/view?usp=sharing) the plots show that the values of PCT_CLAY, PCT_SAND, and ORGANIC do not exist for the first layers after updating. Upon further investigation, we noticed the issue is not with the code and the data provided by neon has some issues. 

For example, in the neon data for [the TOOL site](https://neon-ncar.s3.data.neonscience.org/NEON/surf_files/v1/TOOL_surfaceData.csv) , values of clayTotal, sandTotal, bulkDensExclCoarseFrag( needed for calculating ORGANIC) are missing for some of the layers.

Other sites with similar issues are BARR, BONA, HEAL, PUUM, SOAP, WREF, KONA, LENO, SCBI.

**Comment by ddurden** [comment]
I've added `estimatedOC` to the surface data sets and the description file per discussions in our meeting Ed.

**Comment by wwieder** [comment]
@negin let's have a look at this next week when casper is back up, although I guess we could be working on CGD machines?  Regardless, this is not as high priority as the visualization work right now.

**Comment by wwieder** [comment]
I'm going to resolve this for know, with [plots from @negin513 here](https://drive.google.com/drive/folders/15OpwbTtAleBLikhbfyxfPdfbeMcsfbrA?usp=sharing).

As we look at more output, we may need to revisit these data
